name: suanpan
base: core20
version: "1.2"
summary: An Open Source, Parallel and Heterogeneous Finite Element Analysis Framework
description: |
  [**suanPan**](https://tlcfem.github.io/suanPan/) is a finite element method (FEM) simulation platform for applications in fields such as solid mechanics and civil/structural/seismic engineering. The name **suanPan** (in some places such as suffix it is also abbreviated as **suPan**) comes from the term *Suan Pan* (算盤), which is [Chinese abacus](https://en.wikipedia.org/wiki/Suanpan). **suanPan** is written in modern high quality C++ code and is targeted to provide an efficient, concise, flexible and reliable FEM simulation platform.
grade: stable
confinement: strict
architectures:
  - build-on: amd64
apps:
  suanpan:
    command: bin/suanPan
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
parts:
  mkl:
    plugin: nil
    build-packages:
      - wget
      - cpio
    override-build: |
      wget http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16533/l_mkl_2020.1.217.tgz
      tar -xzf l_mkl_2020.1.217.tgz && cd l_mkl_2020.1.217
      sed -i 's/decline/accept/g' ./silent.cfg
      sed -i 's/\/opt\/intel/\/build\/suanpan\/parts\/mkl\/intel/g' ./silent.cfg
      ./install.sh --silent ./silent.cfg
      export MTO=/build/suanpan/parts/suanpan/install/bin/
      mkdir -p $MTO
      export MFROM=/build/suanpan/parts/mkl/intel/compilers_and_libraries/linux/lib/intel64/
      cp $MFROM/libiomp5.so $MTO
      export MFROM=/build/suanpan/parts/mkl/intel/mkl/lib/intel64/
      cp $MFROM/libmkl_core.so $MTO
      cp $MFROM/libmkl_intel_lp64.so $MTO
      cp $MFROM/libmkl_intel_thread.so $MTO
      cp $MFROM/libmkl_def.so $MTO
      cp $MFROM/libmkl_avx512.so $MTO
      cp $MFROM/libmkl_avx2.so $MTO
      cp $MFROM/libmkl_avx.so $MTO
  vtk:
    source: https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=OFF
    build-environment:
      - CC: gcc-9
      - CXX: g++-9
      - FC: gfortran-9
    build-packages:
      - gcc-9
      - g++-9
      - gfortran-9
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
    stage-packages:
      - libgl1
      - libglvnd0
      - libglx0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
  suanpan:
    after:
      - mkl
      - vtk
    source: https://github.com/TLCFEM/suanPan.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_MULTITHREAD=ON
      - -DUSE_HDF5=ON
      - -DUSE_EXTERNAL_VTK=ON
      - -DVTK_DIR=/build/suanpan/parts/vtk/install/usr/local/lib/cmake/vtk-9.0/
      - -DUSE_MKL=ON
      - -DMKLROOT=/build/suanpan/parts/mkl/intel/compilers_and_libraries/linux/mkl/
    build-environment:
      - CC: gcc-9
      - CXX: g++-9
      - FC: gfortran-9
    build-packages:
      - gcc-9
      - g++-9
      - gfortran-9
    stage-packages:
      - libgfortran5
      - libgl1
      - libglvnd0
      - libglx0
      - libquadmath0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
